### ISSUE TITLE
Unable to read key file: Public key not found error

### ISSUE THREAD

**Issue by bharathnj** [SoftwareAG/webmethods-integrationserver-pgpencryption#2]
Getting  Unable to read key file: Public key not found error in 10.3 version. Both key files are available under /keys. Any suggestions

**Error:**
```
com.wm.app.b2b.server.ServiceException: Unable to read key file: Public key not found
	at pgp.services.keys.readPublicKeys(keys.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by slcom101** [comment]
Hi! did you manage to solve this problem?
`com.wm.app.b2b.server.ServiceException: Unable to read key file: Public key not found
	at pgp.services.keys.readPublicKeys(keys.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.wm.app.b2b.server.JavaService.baseInvoke(JavaService.java:404)
	at com.wm.app.b2b.server.invoke.InvokeManager.process(InvokeManager.java:765)
	at com.wm.app.b2b.server.util.tspace.ReservationProcessor.process(ReservationProcessor.java:39)
	at com.wm.app.b2b.server.invoke.StatisticsProcessor.process(StatisticsProcessor.java:54)
	at com.wm.app.b2b.server.invoke.ServiceCompletionImpl.process(ServiceCompletionImpl.java:243)
	at com.wm.app.b2b.server.invoke.ValidateProcessor.process(ValidateProcessor.java:49)
	at com.wm.app.b2b.server.invoke.PipelineProcessor.process(PipelineProcessor.java:171)
	at com.wm.app.b2b.server.ACLManager.process(ACLManager.java:331)
	at com.wm.app.b2b.server.invoke.DispatchProcessor.process(DispatchProcessor.java:34)
	at com.wm.app.b2b.server.AuditLogManager.process(AuditLogManager.java:379)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:637)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:443)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:399)
	at com.wm.app.b2b.server.ServiceManager.invoke(ServiceManager.java:252)
	at com.wm.app.b2b.server.BaseService.invoke(BaseService.java:229)
	at com.wm.lang.flow.FlowInvoke.invoke(FlowInvoke.java:257)
	at com.wm.lang.flow.FlowState.invokeNode(FlowState.java:535)
	at com.wm.lang.flow.FlowState.step(FlowState.java:401)
	at com.wm.lang.flow.FlowState.invoke(FlowState.java:372)
	at com.wm.app.b2b.server.FlowSvcImpl.baseInvoke(FlowSvcImpl.java:1132)
	at com.wm.app.b2b.server.invoke.InvokeManager.process(InvokeManager.java:765)
	at com.wm.app.b2b.server.util.tspace.ReservationProcessor.process(ReservationProcessor.java:39)
	at com.wm.app.b2b.server.invoke.StatisticsProcessor.process(StatisticsProcessor.java:54)
	at com.wm.app.b2b.server.invoke.ServiceCompletionImpl.process(ServiceCompletionImpl.java:243)
	at com.wm.app.b2b.server.invoke.ValidateProcessor.process(ValidateProcessor.java:49)
	at com.wm.app.b2b.server.invoke.PipelineProcessor.process(PipelineProcessor.java:171)
	at com.wm.app.b2b.server.ACLManager.process(ACLManager.java:331)
	at com.wm.app.b2b.server.invoke.DispatchProcessor.process(DispatchProcessor.java:34)
	at com.wm.app.b2b.server.AuditLogManager.process(AuditLogManager.java:379)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:637)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:443)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:399)
	at com.wm.app.b2b.server.ServiceManager.invoke(ServiceManager.java:252)
	at com.wm.app.b2b.server.BaseService.invoke(BaseService.java:229)
	at com.wm.lang.flow.FlowInvoke.invoke(FlowInvoke.java:257)
	at com.wm.lang.flow.FlowState.invokeNode(FlowState.java:535)
	at com.wm.lang.flow.FlowState.step(FlowState.java:401)
	at com.wm.lang.flow.FlowState.invoke(FlowState.java:372)
	at com.wm.app.b2b.server.FlowSvcImpl.baseInvoke(FlowSvcImpl.java:1132)
	at com.wm.app.b2b.server.invoke.InvokeManager.process(InvokeManager.java:765)
	at com.wm.app.b2b.server.util.tspace.ReservationProcessor.process(ReservationProcessor.java:39)
	at com.wm.app.b2b.server.invoke.StatisticsProcessor.process(StatisticsProcessor.java:54)
	at com.wm.app.b2b.server.invoke.ServiceCompletionImpl.process(ServiceCompletionImpl.java:243)
	at com.wm.app.b2b.server.invoke.ValidateProcessor.process(ValidateProcessor.java:49)
	at com.wm.app.b2b.server.invoke.PipelineProcessor.process(PipelineProcessor.java:171)
	at com.wm.app.b2b.server.ACLManager.process(ACLManager.java:331)
	at com.wm.app.b2b.server.invoke.DispatchProcessor.process(DispatchProcessor.java:34)
	at com.wm.app.b2b.server.AuditLogManager.process(AuditLogManager.java:379)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:637)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:443)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:399)
	at com.wm.app.b2b.server.ServiceManager.invoke(ServiceManager.java:252)
	at com.wm.app.b2b.server.BaseService.invoke(BaseService.java:229)
	at com.wm.lang.flow.FlowInvoke.invoke(FlowInvoke.java:257)
	at com.wm.lang.flow.FlowState.invokeNode(FlowState.java:535)
	at com.wm.lang.flow.FlowState.step(FlowState.java:401)
	at com.wm.lang.flow.FlowState.invoke(FlowState.java:372)
	at com.wm.app.b2b.server.FlowSvcImpl.baseInvoke(FlowSvcImpl.java:1132)
	at com.wm.app.b2b.server.invoke.InvokeManager.process(InvokeManager.java:765)
	at com.wm.app.b2b.server.util.tspace.ReservationProcessor.process(ReservationProcessor.java:39)
	at com.wm.app.b2b.server.invoke.StatisticsProcessor.process(StatisticsProcessor.java:54)
	at com.wm.app.b2b.server.invoke.ServiceCompletionImpl.process(ServiceCompletionImpl.java:243)
	at com.wm.app.b2b.server.invoke.ValidateProcessor.process(ValidateProcessor.java:49)
	at com.wm.app.b2b.server.invoke.PipelineProcessor.process(PipelineProcessor.java:171)
	at com.wm.app.b2b.server.ACLManager.process(ACLManager.java:331)
	at com.wm.app.b2b.server.invoke.DispatchProcessor.process(DispatchProcessor.java:34)
	at com.wm.app.b2b.server.AuditLogManager.process(AuditLogManager.java:379)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:637)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:443)
	at com.wm.app.b2b.server.invoke.InvokeManager.invoke(InvokeManager.java:399)
	at com.wm.app.b2b.server.ServiceManager.invoke(ServiceManager.java:252)
	at com.wm.app.b2b.server.comm.DefaultServerRequestHandler.handleMessage(DefaultServerRequestHandler.java:120)
	at com.wm.app.b2b.server.HTTPMessageHandler.process(HTTPMessageHandler.java:156)
	at com.wm.app.b2b.server.HTTPDispatch.handleRequest(HTTPDispatch.java:183)
	at com.wm.app.b2b.server.Dispatch.run(Dispatch.java:404)
	at com.wm.util.pool.PooledThread.run(PooledThread.java:127)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by njbharathkumar** [comment]
@slcom101 : Yes, there is a small bug in PGPKeyReader.readPublicKeyRing(String path)

`coll = new PGPPublicKeyRingCollection(in);`

should be

`coll = new PGPPublicKeyRingCollection(din);`

Correct this and try. It will work.

**Comment by rakeshadupa** [comment]
hi, @njbharathkumar 
I am unable to decompile and do that change.
Could you please help me with the steps or share the updated JAR with me.
Thanks in advance.

**Comment by njbharathkumar** [comment]
Hi,
Had updated the bug details in GitHub comments. Please check.

Thanks
Bharath

**Comment by rakeshadupa** [comment]
Hi Bharath,
I have seen your comment asking to pass "din" variable instead of "in".
My understanding is the change has to be done inside following method which is available inside pgp_idk.jar
PGPKeyReader.readPublicKeyRing(String path)
 If yes, I am facing issue decompiling jar.
Would you mind sharing the latest code jar?
Thanks.

**Comment by raveeshnanjappa** [comment]
Hi @rakeshadupa, @bharathnj, @slcom101 

How did you fix this issue. I am also getting the same error. Can you please share the steps you follwed to fix this.

Regards,
Raveesh
